name: 'Next.js CloudFront Router Action'
description: 'Update a CloudFront Distribution to route a Next.js app'
branding:
  icon: 'arrow-up-circle'
  color: 'blue'
inputs:
  distribution-id:
    description: The CloudFront distribution ID
    required: false
  function-name-prefix:
    description: The Lambda@Edge function name prefix. Defaults to `{repositoryName}-{distributionId}-`.
    required: false.
  lambda-edge-role:
    description: The Lambda@Edge Role
    required: false
  working-directory:
    description: The working directory
    required: false
    default: '.'
  invalidate:
    description: Invalidate the CloudFront cache at the given path, e.g. '/*' or '/index.html'. If ommitted, the cache will not be invalidated.
    required: false
runs:
  using: 'node16'
  main: 'dist/main.js'
